# Trigger pipeline when changes are made to EXE or MSI files in main branch
trigger:
  branches:
    include:
      - main
      - dev/sign-msi
  paths:
    include:
      - '**/*.exe'
      - '**/*.msi'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'codeSignPrincipal'
    KeyVaultName: 'Kahf-Yazilim-cert'
    SecretsFilter: '*'
    RunAsPreJob: true
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Get the list of changed files in the commit
      $changedFiles = git diff-tree --no-commit-id --name-only -r HEAD

      # Filter for EXE and MSI files only
      $filesToSign = $changedFiles | Where-Object { $_ -like "*.exe" -or $_ -like "*.msi" }
          
      # Set pipeline variables based on found files
      if ($filesToSign) {
        Write-Host "##vso[task.setvariable variable=FOUND_FILES]true"
        $filesToSign | ForEach-Object { Write-Host "##vso[task.setvariable variable=FILE_PATH]$_" }
      } else {
        Write-Host "##vso[task.setvariable variable=FOUND_FILES]false"
      }
  displayName: 'Check for EXE/MSI changes'

- task: DownloadSecureFile@1
  name: signtool
  inputs:
    secureFile: 'signtool.exe'
  condition: eq(variables['FOUND_FILES'], 'true')

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'codeSignPrincipal'
    KeyVaultName: 'Kahf-Yazilim-cert'
    SecretsFilter: '*'
  condition: eq(variables['FOUND_FILES'], 'true')

- powershell: |
    # Sign the file using Azure HSM key
    & "$(signtool.secureFilePath)" sign /fd sha256 /f "$(SIGNING_KEY_NAME)" /tr http://timestamp.digicert.com /td sha256 "$(FILE_PATH)"
  displayName: 'Sign file with HSM key'
  condition: eq(variables['FOUND_FILES'], 'true')

- powershell: |
    git config --global user.email "pipeline@example.com"
    git config --global user.name "Azure Pipeline"
    git add "$(FILE_PATH)"
    git commit -m "Add signed file: $(FILE_PATH)"
    git push origin main
  displayName: 'Push signed file to repo'
  condition: eq(variables['FOUND_FILES'], 'true')