name: Sign EXE Files
on:
  push:
    paths:
      - 'unsigned/*.exe'
      - 'unsigned/*.msi'
      - 'unsigned/*.dll'

  workflow_dispatch:

      
jobs:
  sign-exe:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install AzureSignTool
        run: |
          dotnet tool install --global AzureSignTool
        shell: bash

      - name: Sign EXE and MSI Files
        shell: bash
        run: |
          for file in unsigned/*.{exe,msi,dll}; do
            if [ -f "$file" ]; then
              AzureSignTool sign \
                -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" \
                -kvi "${{ secrets.AZURE_CLIENT_ID }}" \
                -kvt "${{ secrets.AZURE_TENANT_ID }}" \
                -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" \
                -kvc ${{ secrets.AZURE_CERT_NAME }} \
                -tr http://timestamp.digicert.com \
                -v "$file"
              
              # Move signed file to signed directory
              mkdir -p signed
              mv "$file" "signed/$(basename "$file")"
            fi
          done

      - name: Commit and Push Signed Files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add signed/*.exe signed/*.dll
          git add -u unsigned/*.exe unsigned/*.dll
          git commit -m "Sign and move EXE and DLL files"
          git push
        shell: bash

      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
